'use strict';
const { baseTemplate } = require('./baseTemplate');
function newOrderAlertTemplate({ tenant, order, items, customer }) {
  const primaryColor  = tenant.theme_color || '#D97706';
  const formattedDate = new Date(order.created_at).toLocaleString('en-IN', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });
  const itemRows = items.map(item => `<tr><td style="padding:8px 0;border-bottom:1px solid #f0efe9;font-size:14px;">${escHtml(item.product_name)}</td><td style="padding:8px 0;border-bottom:1px solid #f0efe9;font-size:14px;text-align:center;">${item.quantity}</td><td style="padding:8px 0;border-bottom:1px solid #f0efe9;font-size:14px;text-align:right;font-weight:600;">₹${(parseFloat(item.price) * item.quantity).toLocaleString('en-IN')}</td></tr>`).join('');
  const bodyHtml = `<h2 style="margin:0 0 4px;font-size:20px;font-weight:700;font-family:Georgia,serif;">New order received 📦</h2><p style="margin:0 0 24px;font-size:14px;color:#6b7280;">${formattedDate}</p><table role="presentation" width="100%" style="background:#fafaf8;border:1px solid #e5e4df;border-radius:10px;margin-bottom:20px;"><tr><td style="padding:16px 20px;"><p style="margin:0 0 2px;font-size:12px;color:#9ca3af;text-transform:uppercase;">Customer</p><p style="margin:0 0 4px;font-size:16px;font-weight:700;">${escHtml(customer.name)}</p><p style="margin:0;font-size:13px;color:#6b7280;">${escHtml(customer.email)}</p></td><td style="padding:16px 20px;text-align:right;vertical-align:top;"><p style="margin:0;font-size:22px;font-weight:700;color:${primaryColor};">#${order.id}</p></td></tr></table><table role="presentation" width="100%" style="margin-bottom:4px;"><tr><th style="font-size:11px;color:#9ca3af;text-align:left;padding-bottom:6px;">Item</th><th style="font-size:11px;color:#9ca3af;text-align:center;padding-bottom:6px;">Qty</th><th style="font-size:11px;color:#9ca3af;text-align:right;padding-bottom:6px;">Amount</th></tr>${itemRows}<tr><td colspan="2" style="padding:12px 0 0;font-size:15px;font-weight:700;">Total received</td><td style="padding:12px 0 0;font-size:18px;font-weight:700;color:${primaryColor};text-align:right;">₹${parseFloat(order.total_price).toLocaleString('en-IN')}</td></tr></table>`;
  const text = [`NEW ORDER — ${tenant.name}`, `Order #${order.id} | ${formattedDate}`, '', `Customer: ${customer.name}`, `Email: ${customer.email}`, '', 'ITEMS:', ...items.map(i => `  ${i.product_name} x${i.quantity}  ₹${(parseFloat(i.price) * i.quantity).toLocaleString('en-IN')}`), '', `TOTAL: ₹${parseFloat(order.total_price).toLocaleString('en-IN')}`].join('\n');
  return { subject: `🧁 New order #${order.id} — ₹${parseFloat(order.total_price).toLocaleString('en-IN')} from ${customer.name}`, html: baseTemplate({ tenant, title: `New order #${order.id}`, preheader: `${customer.name} ordered ₹${parseFloat(order.total_price).toLocaleString('en-IN')}`, bodyHtml }), text };
}
function escHtml(str) { return String(str ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'); }
module.exports = { newOrderAlertTemplate };
